### ISSUE TITLE
Missing OUnit Id

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-iias#11]
@wrygiel : 
Shouldn't there be an optional `ounit-id` at the top and partner-hei levels, as IIAs can have OUnits as Partners?

**Comment by wrygiel** [comment]
There are the `sending-ounit-id` and `receiving-ounit-id` on the MobilitySpecification level. Do you think it's not enough?

**Comment by kaiqu** [comment]
> There are the sending-ounit-id and receiving-ounit-id on the MobilitySpecification level. Do you think it's not enough?

In the model, the IIA Partners themselves are OUnits - i.e. an IIA is technically between OUnits (possibly top-level units representing the HEI). Cooperation Conditions reference a Sending and Receiving Partner (i.e. OUnit) within an IIA. This means a lower-level OUnit (e.g. a department) has to be registered as an IIA Partner to be referenced in Cooperation Conditions for that IIA.

The format specifies only HEIs as IIA Partners, and no constraints on the OUnits used in MobilitySpecification (which is roughly equivalent to Cooperation Condition).

There seems to be 3 alternatives here:
1. Conform the model to the format
2. Conform the format to the model
3. A compromise:
   - Include the possibility of OUnits as IIA Partners in the format (renaming "partner-hei" to "partner")
   - Allow any OUnits in Cooperations if the Partner is on the HEI level

What do you think?

**Comment by wrygiel** [comment]
I think we need some input from SOP, because I think they are the only ones who have dealt with ounit-level IIAs.

Let's say we have an IIA with three partners:

1. HEI A,
2. OUnit B1 of HEI B,
3. OUnit B2 of HEI B.

Questions for @georgschermann:

* Do you know who actually signs the paper version of such IIA? Will it have two signatures or three?
* Which database model do you use in SOP? (In Poland, IIAs are always between HEIs.)

Referencing external ounits will always be more problematic than referencing HEIs, because ounit IDs are always set by the ounit's HEI (while HEI ID can be deduced without the remote HEI's help). In practice, I kind of expect, that the implementers will strongly prefer to NOT be forced to expose remote ounit-ids at all (because we would require these IDs to be confirmed by the ounit's HEI).

**Comment by georgschermann** [comment]
In our database we reuse the same entities for HEIs and OUnits which include a parentId to model the relation between them. HEIs don't have to be top level entries in our system, since it also contains consortia, for which the participating HEIs behave like OUnits. So HEIs and OUnits can be equally used as IIA partners.

When generating an IIA where 2 OUnits of one HEI would participate as different partners (what never occured so far I think) there would be a signature stored per partner, so 3 signatures. But it would be possible that the same signature would be used by B1 and B2, if a person from the parent HEI is configuered as the signee.

The most common case is, that small universities have their agreements per HEI and larger universities have  them per faculty or department and so agreements often are between a HEI and an OUnit.

I think when the external HEI exposes their OUnits via the API then it should be possible to use the OUnits id as an IIA partner, in cases where the OUnits are not exposed the HEI would be the partner.

**Comment by kaiqu** [comment]
> In our database we reuse the same entities for HEIs and OUnits which include a parentId to model the relation between them.

Exactly like the data model.

> HEIs don't have to be top level entries in our system, since it also contains consortia, for which the participating HEIs behave like OUnits.

This indicates a generalized hierarchical structure of OUnits, where
- the top level usually (but not always) is a HEI,
- HEIs can be at lower levels, and
- any level can be an IIA Partner.

The model needs very little tweaking to express this:
- Rename "Inst/Org Unit" to "Org Unit" (or "OUnit", to conform to the APIs)
- Introduce a "Unit Type" label to signify HEI, Department, Consortium etc.

How much work would it be to express this in the APIs?
Do we really need separate APIs for HEIs and OUnits anymore?

> When generating an IIA where 2 OUnits of one HEI would participate as different partners (what never occured so far I think) there would be a signature stored per partner, so 3 signatures.

Which is modeled by having the Signing Date in IIA Partner ("Inst/Org Unit as partner in IIA").

> The most common case is, that small universities have their agreements per HEI and larger universities have  them per faculty or department and so agreements often are between a HEI and an OUnit.
> I think when the external HEI exposes their OUnits via the API then it should be possible to use the OUnits id as an IIA partner, in cases where the OUnits are not exposed the HEI would be the partner.

I agree.

**Comment by wrygiel** [comment]
> I think when the external HEI exposes their OUnits via the API then it should be possible to use the OUnits id as an IIA partner, in cases where the OUnits are not exposed the HEI would be the partner.

Okay, so we will add optional ounit-id to IIA partner elements.

> Do we really need separate APIs for HEIs and OUnits anymore?

This is off-topic again, but it's **far** too late to change this now. Remember that many developers have already started implementing those. These APIs have been designed separately from the start (almost a year ago), and there were no objections from any partner, so I'm quite certain this is compatible with all partners' models.

**Comment by kaiqu** [comment]
>> Do we really need separate APIs for HEIs and OUnits anymore?
> 
> This is off-topic again, but it's **far** too late to change this now. Remember that many developers have already started implementing those. These APIs have been designed separately from the start (almost a year ago), and there were no objections from any partner, so I'm quite certain this is compatible with all partners' models.

But what about @georgschermann 's case of consortia with underlying HEIs? One solution could be to express a consortium as a dummy HEI, and its HEIs as dummy OUnits (essentially duplicates of the HEIs themselves). Or are consortia out of scope for the time being?

**Comment by wrygiel** [comment]
> are consortia out of scope for the time being?

Yes.

**Comment by wrygiel** [comment]
> But what about @georgschermann 's case of consortia with underlying HEIs?

BTW, I don't think Georg suggested changing this (adding consortia to EWP)? As I understood it, he simply described his internal model (because we asked him to).

**Comment by kaiqu** [comment]
> Okay, so we will add optional ounit-id to IIA partner elements.

How about the top level? The partner-hei element represents **other** partners, but the responding partner could also be an OUnit, so I believe it's necessary to add an optional ounit-id at the level of iia-id as well?

**Comment by wrygiel** [comment]
> I believe it's necessary to add an optional ounit-id at the level of iia-id as well?

Yes, you're right. So two new elements will be added.

**Comment by kaiqu** [comment]
I also suggest renaming "partner-hei" to the more general "partner".

**Comment by wrygiel** [comment]
> I also suggest renaming "partner-hei" to the more general "partner".

I agree!

**Comment by wrygiel** [comment]
@kaiqu, it's not a good idea to close issues before they are actually fixed ;)
