### ISSUE TITLE
Can once mutually approved IIA be deleted ?

### ISSUE THREAD

**Issue by anant6767** [erasmus-without-paper/ewp-specs-api-iias#163]
"An IIA that has not been mutually approved can be deleted by removing it from the EWP network."
Above statement is mentioned in spec.
 
I have question related to this.
 
Assume IIA A is from partner 1 and IIA B is from partner 2.
Both is linked and mutually approved.
After that, partner 1 did some change in IIA A and shared.
Now IIA A and IIA B is no longer mutually approved IIA.
Can we delete IIA A?

**Comment by janinamincer-daszkiewicz** [comment]
I assume that you talk about v7. 
When one of the partners enters the negotiation mode (presents some changes to the partner) it does not mean that this IIA stops beeing mutually approved - it is. And it will stay that way because partners either revert to the previous version or will approve a new version.
Once mutually approved IIA will never be deleted.

**Comment by umesh-qs** [comment]
> I assume that you talk about v7. When one of the partners enters the negotiation mode (presents some changes to the partner) it does not mean that this IIA stops beeing mutually approved - it is. And it will stay that way because partners either revert to the previous version or will approve a new version. Once mutually approved IIA will never be deleted.

"Once mutually approved IIA can never be deleted". This must be mentioned clearly in the specification, to avoid any confusion.

**Comment by umesh-qs** [comment]
Looks like @janinamincer-daszkiewicz  is in a hurry to close the issues. Can we please add this point clearly in the specs. If it is already mentioned then please point me to the same.
