### ISSUE TITLE
Is termination as a whole the end-state or not?

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#165]
If an IIA is terminated as a whole and this termination has been mutually approved, is it allowed to create another revision and revert this termination?

Since I haven't found that this would be explicitly forbidden anywhere in the specification, I assume that it might be forbidden implicitly, i.e. by inferring this conclusion from the fact that the scenario for termination provided at https://github.com/erasmus-without-paper/ewp-specs-api-iias/raw/stable-v7/scenarios-v6-v7/2023-12-01-TerminatedAsWhole.xlsx does not include reversion. However, such a conlusion does not seem definitive to me because we could also infer that such a scenario is missing because it is already obvious how the reversion generally works from https://github.com/erasmus-without-paper/ewp-specs-api-iias/files/14006300/2024-01-20-DeleteModifyScenarios.xlsx

@janinamincer-daszkiewicz Can you help me understand whether we as implementers should interpret the specification in this way: "Whatever is not clearly defined, is allowed." or "Whatever is not clearly defined, is forbidden"?

My apologies if this quandary has a clear explanation somewhere in the current specification, in which case I would like to ask for a link to the exact location where this is clarified.

**Comment by umesh-qs** [comment]
There is no end state for an IIA. IIA can be changed forever.
Something we opposed, but DG EAC thinks otherwise.

**Comment by jiripetrzelka** [comment]
> There is no end state for an IIA. IIA can be changed forever.
> Something we opposed, but DG EAC thinks otherwise.

@umesh-qs Can you please provide a link or more information as to when and where this position of DG EAC was articulated?

**Comment by umesh-qs** [comment]
> > There is no end state for an IIA. IIA can be changed forever.
> > Something we opposed, but DG EAC thinks otherwise.
> 
> @umesh-qs Can you please provide a link or more information as to when and where this position of DG EAC was articulated?

As far as I remember, it was discussed in one of the IF calls.

**Comment by janinamincer-daszkiewicz** [comment]
1. Mutually approved IIAs can be modified (but eventually reverted to the approved version if negotiations are not successful).
2. Termination as a whole is a special case of modification, where changes happened so early that no mobilities had yet been created.
3. For the technical reason we call it differently (terminated as a whole and not just modification) and process differently (with a special attribute). (_Jiri, you were the one who discovered this special case._)
4. If BPOs decided that they need functionality of modification, they need it for any type of modification (also this special case). When providers voted for the option how to implement Terminated as a whole, they have chosen a solution where the content of IIA (all CCs) stay intact, which in particular enables further modifications.
5. Practically speaking, I don't think that users will often go this way, i.e. terminate IIA as a whole (even this will be rare) and then resume it. But why should we prohibit them from doing so, if such a need may arise and we will have an implemented mechanism for it (because we are implementing the modification anyway).

**Comment by jiripetrzelka** [comment]
I have looked again at slides from IFs and I have found out that we, in fact, voted for the option that terminated-as-a-whole will not be an end state. 

This chart is taken from slide 38 of 2023-06-21-InfrastructureForum.pdf at https://esci-sd.atlassian.net/wiki/spaces/ITSC/pages/113999873/Infrastructure+Forum+and+technical+workshops

![image](https://github.com/erasmus-without-paper/ewp-specs-api-iias/assets/1330161/659f73ad-2145-4a1c-b7a0-7c0de6f2a78d)

I presume DG EAC then accepted these results and that is probably what Umesh refers to.

@janinamincer-daszkiewicz If I take your point 5 and the results of the voting, my conclusion is that systems are required to be prepared for this scenario. Can you please confirm this?

**Comment by janinamincer-daszkiewicz** [comment]
> @janinamincer-daszkiewicz If I take your point 5 and the results of the voting, my conclusion is that systems are required to be prepared for this scenario. Can you please confirm this?

Yes, I confirm.
