### ISSUE TITLE
Only 1 ISCED code limitation

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-iias#26]
IIA API allows only 1 isced-f-code (**<xs:element name="isced-f-code" type="xs:string" minOccurs="0" maxOccurs="1">**) at a time? Any particular reason for this restriction? What to do if the agreement allows more then 1 ISCED code?

**Comment by MartaJuzepczuk** [comment]
Currently there is one ISCED code for every cooperation condition. But you are probably right, we should allow many.

**Comment by georgschermann** [comment]
in our case if the agreement has multiple ISCED codes we repeat the coop-conditions for each ISCED code. Allowing multiple ISCED codes could reduce the size of the response. I think this granularity was chosen, because some partners stored the agreements on ISCED level.

**Comment by umesh-qs** [comment]
"I think this granularity was chosen, because some partners stored the agreements on ISCED level". Even in this case we can allow more then one ISCED codes and then these partners can split is when saving in their database

**Comment by janinamincer-daszkiewicz** [comment]
Marta, let's do this change if it is needed.

**Comment by MartaJuzepczuk** [comment]
Resolved in https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/c22b7917774a265aed3acd40891d0a4771a338c0

**Comment by georgschermann** [comment]
we noticed an issue here during testing which would need clarification @umesh-qs @janinamincer-daszkiewicz 
how are multiple ISCED codes related with the field mobilities-per-year?
is it mobilities-per-year-per-isced or is the number of mobilities for all isced codes?

> "I think this granularity was chosen, because some partners stored the agreements on ISCED level". Even in this case we can allow more then one ISCED codes and then these partners can split is when saving in their database

If the numbers are for all ISCED codes this would prevent partners from spllitting up the agreement.
If it is mobilities-per-year-per-isced I think it won't be applicable in many cases.

For us the mobilities-per-year-per-isced would be OK but practically never be used, since the numbers almost never match exactly. 
in the case of mobilities for all isced codes we would change it to different coop-conditions with specific numbers for each isced code upon import and most likely never work with multiple isced codes.

**Comment by kamil-olszewski-uw** [comment]
Definitely, it's the number of mobilities for all ISCED codes.

If there is a separate mobilities pool for each ISCED, this should be defined using separate cooperation conditions.

Multiple ISCED codes defined under one cooperation conditions are useful when, for example, fields of study of cooperating faculties cover more than one ISCED field. For us, this is a very rare situation, but it does happen sometimes.
