### ISSUE TITLE
How to know Receiver Institutions Academic Year Format?

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-iias#27]
In IIA API <receiving-academic-year-id> is supposed to be in format of receiving institution. Is there a API that tells in what format the receiver institution is accepting the academic year? If not, then how will sender institution know the format?

**Comment by MartaJuzepczuk** [comment]
Currently there is no such API. We theoretically allow two formats, but, to my knowledge, every European HEI uses the same. Maybe assuming that the sending institution knows somehow the format, is sufficient for now?

**Comment by umesh-qs** [comment]
I am not sure how assumption will work here. This field is mandatory in the API. To share a particular IIA in EWP, this field has to be filled by our clients. It is crazy to expect them to know their clients academic year format and fill accordingly.

Is there a reason why this is needed? And why is it mandatory?

**Comment by wrygiel** [comment]
If we're talking about [`<receiving-academic-year-id>`](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/ed54908c4e2bc986d052255a19103600ad707981/endpoints/get-response.xsd#L364), then it's mandatory, because - as far as I remember - it's not possible to have a valid IIA agreement without specifying the academic year of such agreement.

I think clients should be aware of the format. They will need to in order to actually sign the agreement with the other HEI (the one in the southern hemisphere).

Since all members are in the northern hemisphere so far, it's perfectly safe to assume that your format is the same as the other HEI's.
