### ISSUE TITLE
Academic year list is in sequence?

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-iias#28]
I see below issue raise earlier
https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/12

And it was decided that the list will be kept because 2 of the partners keep list in their system. 

I just wanted to check if the list will be in sequence always, so that partners who are using span can easily take first and last entry. If not the may be we should re-look to pass it in span and not list

**Comment by wrygiel** [comment]
I don't think so. If these two partners always would keep it in sequence (e.g. 2006, 2007, 2008), then they wouldn't need a list in the first place.

If you receive an IIA with a broken sequence (e.g. 2006, 2007, 2009), and you don't support it, then you might need to dynamically break it into multiple IIAs on your side (e.g. one for 2006-2007, and the second one for 2009-2009).

**Comment by umesh-qs** [comment]
@kamil-olszewski-uw 
Is this a practical scenario, with cooperation conditions not having academic years in sequence. Are universities creating agreements like this?

**Comment by umesh-qs** [comment]
@kamil-olszewski-uw 
If an agreement is created today, what would be the business case that will require skipping a year between a year range?

**Comment by kamil-olszewski-uw** [comment]
When it was discussed a few years ago, the point was that some systems theoretically allow such gaps.

Then it was discussed in #10 and #12.

We don't have (and don't allow) such gaps in our system. If the partner university proposes them to us, we will ask for splitting cooperation conditions to two entities, and in the worst case we will not accept such an agreement. But we don't mind that the API allows it.

**Comment by umesh-qs** [comment]
It is not about what the individual systems allow. If we go by that then why was ounit restricted to 1 from multiple? We allow multiple ounit and we will want it in API. Some other systems too. But the justification given was that it was not practical and you have seen thousands of agreements and found not find the use case. Same logic should be applied here. Why having different yardstick for this case?

**Comment by EvelienRenders** [comment]
I agree with @umesh-qs ; allmost all agreements are for the whole sequence, but that's also because the signing process was always such a hassle. SIgning can be done much quicker in the future, which opens up the possibility to change the IIA for one year to accommodate 'fixing' a balance issue for example. That would mean that one year we allow more students to come, but after we go back to the old conditions. 

Right now in Osiris this wouldn't look pretty, because we use sequences. 
![image](https://user-images.githubusercontent.com/45844175/112628471-3ba3d100-8e33-11eb-8ffe-bfcf4b1a97af.png)

The question remains who will decide on this? Is the EWP consortium/project group still intact to decide about these things? I also saw the tender for ESC-initiative from DG EAC - I'm guessing that the further development of the API's is a part of this tender.
