### ISSUE TITLE
Total months calculation question

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-iias#43]
Hi all,

We would like to verify the total months calculation for our IIA data to be published via EWP and therefore needs a sample formula and verification for our following calculation below.

Here is the definition reference for total months.
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response.xsd#L513

And here is the sample XML for iia-get response:
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response-example.xml#L100

Q1: Does the total months given in the above xml response reflect a correct result/calculation/formula?

Q2:  What is the duration in months per person per academic year in the above xml response?

Q3: Is the following calculation correct?

+ We have 4 mobilities per year. 
+ Each mobility duration is 4 months. 
=> That makes 16 months in a year. 

+ The agreement is valid for 4 academic years. 
Shall we print 64 months (4 academic years X 16 months)?

Thanks in advance,

**Comment by EvelienRenders** [comment]
Hi @sascoms,

> Q1: Does the total months given in the above xml response reflect a correct result/calculation/formula?

I'm not sure what you mean. I'm guessing that this is a possible correct result, yes. 70 months/year to be divided over a total of 10 student traineeship mobilities per year. 
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response-example.xml#L94

> Q2: What is the duration in months per person per academic year in the above xml response?

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response-example.xml#L99

That is to be decided between the parties. This example only says that:
- the Norwegian University College will accept 10 students who are coming for a traineeship from Warsaw, Poland
- The subject area of the traineeship should be 0314
- the total of 70 months may be divided over these students, it's a bit of a weird number of months. If you are calculating with a semester of 5 months, you could say there will be 4 students who go for a whole year (10 months x 4) and there are 6 students who go for a semester (5 months x 6), which comes to a total of 70 months.
Then again, traineeships often don't conform to these semesters, but that it is not such a strict rule. This is just a prediction and an agreement of what the two partners are willing to accomodate

> Q3: Is the following calculation correct?
> - We have 4 mobilities per year.
> - Each mobility duration is 4 months.
> => That makes 16 months in a year. 
> - The agreement is valid for 4 academic years. 
> Shall we print 64 months (4 academic years X 16 months)?

I'd recommend always calculating with the standard of 5 months per semester, just because that's the most widely accepted. But if you really mean 4 months per student, then it would have to be <total-months>16.00</total-months>

That's how I understand it. If you have any more questions, feel free!
Kind regards,
Evelien

**Comment by hwManSop** [comment]
Hello everyone,

I would also like to have some clarification on this.
Since it seems everyone doesn't do this the same way.

We have an agreement with someone and in our existing datastructure we have the months of the exchange defined for one year.
In the specification for 'total-months' it says: 'Total number of mobility months, for all academic years bound to the mobility specification." Which we interpret as that this should be the value covering ALL academic years. So when we generate the XML for the IIA we multiply our months with the amount of academic years, our partner however does not.

In contrast to the field 'mobilities-per-year' which explicitly mentions in the description '... ***for each*** academic year...'

Can we have a statement on how this field should be filled please? @janinamincer-daszkiewicz

Best regards,
Manuel

**Comment by mkurzydlowski** [comment]
I'm not able to go through this discussion right now but I would like to point out that I've made some changes according to @kamil-olszewski-uw specification in the soon to be stable version https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/42460f7f482dc771aa359e6933f2794ee7275e77.

**Comment by hwManSop** [comment]
Hello @mkurzydlowski, 

I just noticed the change in the new version, thanks that should clarify things.

Best regards,
Manuel
