### ISSUE TITLE
[Example] How is B supposed to find out A's iia-id?

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-specs-api-iias#57]
I'm having a hard time understanding how `B` is supposed to behave in [the example](https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v6/example-scenario).

Starting with the following examples:

* 2 HEIs can negotiate an arbitrary number of active IIAs between the 2 of them

Step `3` states: "B agrees with the version sent by A"

Now, how is B supposed to link its own version of the IIA to A's version of the IIA? Is this meant to be a manual interaction on B's side?

Furthermore: in step `6` B suddenly knows, that its own `79364` is the counterpart for A's `0f7a5682-faf7-49a7-9cc7-ec486c49a281`. Again: is this determined by manual human interaction with B's system?

Finally: How is all of this supposed to work if one (or both) HEI does not implement [ewp-specs-api-iias-approval](https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval)? The statement [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/55aa7276dbc54a01397cfa3040f053d5c5d926b4/endpoints/get-response.xsd#L241-L244) together with `minOccurs="0"` leads me to believe `ewp-specs-api-iias-approval` is not mandatory.

**Comment by kamil-olszewski-uw** [comment]
Step 3: B needs to save A's iia-id in its system along with its own copy of the entire IIA. Whether it will be manual or automatic depends on the implementation in the system.

In our implementation, if the IIA does not exist in our system and we save the entire IIA received from the partner, the partner IIA is automatically saved in the same action. And if we have our local copy of IIA (traditionally entered outside EWP) and the user believes that IIA in the partner's system is the "twin brother" of our IIA, then the user has the option of manually copying the partner id to our IIA (in fact the user copies the IIA partner's code which is more readable than id, but underneath the system copies the id).

Step 6: B knows A's IIA id since step 3 and keeps that id in its copy of IIA. Responding to A's get request, it sends the IIA with both ids.

It cannot work without implementing the Interinstitutional Agreements Approval API. The "conditions-hash" element is optional because it can be omitted as long as the details of IIAs are being negotiated.

**Comment by j-be** [comment]
Thanks for the reply.

> Whether it will be manual or automatic depends on the implementation in the system.

I see, so on any given pair `X` and `Y` of an IIA, where `X` is `HeiA`'s representation and `Y` is `HeiB`'s representation, at least one needs to be linked to the other manually (i.e. either `HeiA` manually adds `Y`'s ID to `X` or `HeiB` adds `X`'s ID to `Y`), or am I failing to see the mechanism which would allow automatic linking?

> It cannot work without implementing the Interinstitutional Agreements Approval API

Does that mean Interinstitutional Agreements Approval API is mandatory?

> The "conditions-hash" element is optional because it can be omitted as long as the details of IIAs are being negotiated.

In that case I find the passage [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/55aa7276dbc54a01397cfa3040f053d5c5d926b4/endpoints/get-response.xsd#L241-L244) is highly misleading.

**Comment by kamil-olszewski-uw** [comment]
In a scenario where both partners entered IIA into their system outside the EWP network, at least one side must add partner's IIA id manually.

However, if A typed IIA traditionally, and B downloaded it, then B automatically has both IIA ids in its system. Then B will send the CNR with its IIA id. When A does get request, B sends IIA with both ids. This allows A to automatically add B's id to its copy of IIA.

Technically, the Approval API is required to accept IIAs. As for the official information on the required EWP APIs, people more entitled to such statements than me should comment on this.

**Comment by muratyuceer** [comment]
To be sure if there will be a problem with your systems.

According to my scenario
A created new agreement in him local system and call B'n cnr api. After B (if happy) user select Aprove button in own system. In this case i call A's cnr api (for notify new B iia id) and after immediately i call A's aprove cnr api.

In this case, if you process my system requests in parallel, problems may occur right? **(You cant call my aprove cnr api without know my iia id even my aprove api result correct)**

**Comment by kamil-olszewski-uw** [comment]
In your scenario:

1. A creates IIA.
2. A sends IIA CNR request to B with a-iia-id.
3. B saves IIA in its system with a-iia-id and b-iia-id.
4. B sends IIA CNR request to A with b-iia-id.
5. B immediately sends IIA Approval CNR request to A.
6. A processes two B'S CNR requests in parallel:
- A sends IIA get request to B with b-iia-id. B sends get response with a-iia-id and b-iia-id. A binds b-iia-id with its copy of IIA.
- A sends IIA Approval get request to B with a-iia-id. B knows that IIA with b-iia-id has a-iia-id in A's system. B sends get response with a-iia-id. A doesn't have to know b-iia-id to check whether B has accepted its local copy of agreement.

**Comment by muratyuceer** [comment]
Thanks for reply

> A sends IIA get request to B with a-iia-id.

I thought get api could only be called with the id of the partner iia-id. Thanks.

**Comment by muratyuceer** [comment]
@kamil-olszewski-uw I have another question for your request example

> A sends IIA get request to B with a-iia-id.

Can you specify request parameters.

I tought two possibility

**hei_id=b_hei_id & iia_id=a-iia-id**
In this case i cant find correct data because a-iid-id could duplicate with others unless requested hei_id is specified. I understand from here, hei_id must be the owner of the submitted iia_id in request. So let's consider the second scenario

**hei_id=a_hei_id & iia_id=a-iia-id**
In this case my host have multiple tenants, and they may be hosted in different databases. I'm losing the hei information the request will be forwarded to.. I have to scan all my hosts OR i will call A's get api (in my get api progress) and i will find where you want to go 😕 

Do i understand correctly?

**Comment by kamil-olszewski-uw** [comment]
My mistake! In the first subsection of point 6 there should be the sentence: "A sends IIA get request to B with b-iia-id.". I've already corrected the scenario. Sorry!

**Comment by muratyuceer** [comment]
No problem. In that case;

> A sends IIA get request to B with b-iia-id

At this stage, A may not know b-iia-id (because of parallel processing) that's what i wanted to ask. There may be a problem if the other (aprove cnr) request is processed without completing the operation caused by the cnr request. Because will get the b-iia-id when cnr is complete.

**Comment by kamil-olszewski-uw** [comment]
The two processes of step 6 are completely independent of each other and can be performed in any order or simultaneously. If approval CNR request is processed first, A will send IIA approval get request and find out that B accepted IIA. You don't need b-iia-id for anything.

A will send IIA get request only after receiving IIA CNR with b-iia-id from B. As a result, A learns that IIA with b-iia-id is the twin brother of his IIA with a-iia-id.

**Comment by muratyuceer** [comment]
I understand , when an institution's system receives an approval cnr request, it should not give an error if it does not have the id of the other institution yet. Some systems can try to call approval cnr automatically if approval get result correct. I wanted to make sure they shouldn't throw an error when this situation occurs.

Thanks
