### ISSUE TITLE
How non-EWP HEIs should be referenced in IIAs?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#6]
Currently Instutions API returns information only about the HEIs covered by the host serving this API. However, IIAs may refer to other HEIs too. This might be a problem, because the client won't be able to retrieve data on these HEIs (even the basic data, such as HEI's name).

Possible solutions:

1. Include HEIs' names in IIAs API.
2. Allow to describe these HEIs via Institutions API.
3. Limit HEIs exposed via IIAs API to EWP HEIs only.

@erasmus-without-paper/all-members

**Comment by georgschermann** [comment]
We'd suggest 2 or 3.
2 would allow information about HEIs which are not part of EWP to be retrieved from EWP hosts not covering these HEIs but knowing these HEIs. For example the owner of the IIA could be asked about all participating HEIs.
3 should also be good, since the relevant HEIs for the exchange would always participate in EWP otherwise the exchange via EWP isn't possible.

**Comment by wrygiel** [comment]
It also possible to reference non-EWP Organizational Units in IIA. This means that solution 2 would also touch Organizational Units API.

**Comment by wrygiel** [comment]
@georgschermann, could you please review the three comments referenced above?
