### ISSUE TITLE
Language of instruction 1 and 2 (iia template) and recommended-language-skill (ewp)

### ISSUE THREAD

**Issue by tsiakmaki** [erasmus-without-paper/ewp-specs-api-iias#67]
According to the IIA template, a language has some kind of "type": `Language of instruction 1` or `Language of instruction 2`. 

The current spec has the `recommended-language-skill` element, i.e. a list of recommended language skills. Are they all supposed to be `Language of instruction 2`?

**Comment by kamil-olszewski-uw** [comment]
The `recommended-language-skill` element in the API corresponds to `Language of instruction 1` or `Language of instruction 2` in the template. If the template specifies two languages of instruction, two instances of `recommended-language-skill` are needed in get response. The API also allows you to define more than two languages, if necessary.

**Comment by tsiakmaki** [comment]
```
Recommended language skills

| Receiving | Language of instruction 1 | Language of instruction 2  | Student Mobility for Studies           | 
| hei A     | Greek                     | English                    | C1 - Effective Operational Proficiency |
| hei A     | Greek                     | German                     | B2 - Vantage                           |
| hei B     | German                    | English                    | C1 - Effective Operational Proficiency |
| hei B     | German                    | German                     | B1 - Threshold                         |
```

1. Are both `Language of instruction 1` and `2` mandatory at the template?
2. In case the above example stands, could you please write the related parts of the get-response.xsd?
3. Also the template seems to supports different `subject areas` per  language skill. How is this represented?

**Comment by kamil-olszewski-uw** [comment]
Ad 1. I believe it is not so. There is no reason why each cooperation conditions should require students to know two specific languages. There has never been such a requirement.

Ad 3. Optional subject area of language skill is represented in get reponse by `subject-area` subelement inside `recommended-language-skill` element:

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/b8aed419061eba1b86c57389299841114bf500b1/endpoints/get-response.xsd#L447

**Comment by kamil-olszewski-uw** [comment]
Ad 2. The recommended language skills in the IIAs API are not common to the entire agreement, but are defined separately for each cooperation conditions. Let's suppose that each row in your table describes separate cooperation conditions and they concern studies.

```
<cooperation-conditions>
            <student-studies-mobility-spec>
                <sending-hei-id>hei B</sending-hei-id>
[...]
                <receiving-hei-id>hei A</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>el</language>
                    <cefr-level>C1</cefr-level>
                </recommended-language-skill>
                <recommended-language-skill>
                    <language>en</language>
                    <cefr-level>C1</cefr-level>
                </recommended-language-skill>
[...]
            </student-studies-mobility-spec>
            <student-studies-mobility-spec>
                <sending-hei-id>hei B</sending-hei-id>
[...]
                <receiving-hei-id>hei A</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>el</language>
                    <cefr-level>B2</cefr-level>
                </recommended-language-skill>
                <recommended-language-skill>
                    <language>de</language>
                    <cefr-level>B2</cefr-level>
                </recommended-language-skill>
[...]
            </student-studies-mobility-spec>
            <student-studies-mobility-spec>
                <sending-hei-id>hei A</sending-hei-id>
[...]
                <receiving-hei-id>hei B</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>de</language>
                    <cefr-level>C1</cefr-level>
                </recommended-language-skill>
                <recommended-language-skill>
                    <language>en</language>
                    <cefr-level>C1</cefr-level>
                </recommended-language-skill>
[...]
            </student-studies-mobility-spec>
            <student-studies-mobility-spec>
                <sending-hei-id>hei A</sending-hei-id>
[...]
                <receiving-hei-id>hei B</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>de</language>
                    <cefr-level>B1</cefr-level>
                </recommended-language-skill>
[...]
            </student-studies-mobility-spec>
```

In your example, German is unnecessarily repeated in the last line. In get response, you only need to send it once, which I included in the code above.

Please also note that the IIAs API is more flexible than the template table, because for individual cooperation conditions, we can send more than one language through EWP, and each language can have a different recommended level. This should be taken into account when designing the appropriate mechanisms and interface in the system.

**Comment by tsiakmaki** [comment]
Thank you very much Kamil for your replies. 

Given the above code: 
4. Does every row in the Recommended language skills represent a different mobility-spec? The template example represents 2 student-studies-mobility-specs: the one where the receiving is hei A and the one where the receiving is hei B.
5. Does the Language of instruction 1 have level? Doesn't it represent the official language of the receiving Hei?

**Comment by kamil-olszewski-uw** [comment]
Ad 4. In template table, not necessarily each row represents different cooperation conditions, because template is less flexible than EWP API (one language pool for the entire IIA). Therefore, when implementing a system interface, we should not try to duplicate the template table, but simply define a list of language skills for each cooperation conditions.

Ad 5. I don't think that in the template table the level only applies to language 2, and language 1 has no level and it's always the official language of receiving HEI. I have never come across such information anywhere. Anyway, knowledge of the official/native language of receiving HEI is not always required. Sometimes it is only English.

**Comment by tsiakmaki** [comment]
Apologies if I misunderstood something, but I do not think that sending a different mobility spec (in our example above <student-studies-mobility-spec/>) for each language row of the template is flexible. 
We are going to send multiple times the same info of objects like: 
```
<sending-hei-id />
<receiving-hei-id /> 
<receiving-academic-year-id /> (a lot of them..)
<subject-area />
<total-months-per-year />
<eqf-level />
<mobilities-per-year />
<total-months-per-year /> 
...
```
Above, apart from the `<recommended-language-skill />` items, all the rest are the same when it concerns the same sending hei. This is an error prone process that it would result in dublicate rows at the 'Mobility numbers per academic year' tables. 

I thought it was clear that each row of the template that concern the same receiving hei is going to be one `<student-studies-mobility-spec/>` (or/and  `<staff-teacher-mobility-spec/>)`. 

Also, I asked again our IRO department and I was assured that the `Language of Instruction 1` represent the official/native language of receiving hei, and in some cases they might be more than one (e.g. Belgium). 

I would suggest to specify that at the EWP we send only `Language of Instruction 2` recommended language skills. If not, I would suggest to give various related examples.

**Comment by kamil-olszewski-uw** [comment]
The point is not to duplicate the cooperation conditions for every row with languages ​​in the template.

The idea is to define a separate set of languages ​​for each cooperation conditions and not to think in terms of language 1 or language 2 at all.

Imagine that one of the sides of the IIA is uw.edu.pl - the Faculty of Philology, and the other side is auth.gr. In case you are sending HEI and we are receiving HEI, agreement has separate cooperation condtions for:

- Bachelor studies - Swedish philology - English B2 required - we do not require the knowledge of Polish from young students (which is common in IIAs in the case of less popular languages ​​such as Polish).
- Doctoral studies - Russian philology - English B2, Polish A2 and Russian B2 required - PhD students are required to have certain knowledge of the Polish language and knowledge of the language of the literature they study.
- Staff teachers - Greek philology - English C1 required - we only require knowledge of the English language in which the lectures will be conducted, but we do not have the right to demand the Polish language, and we do not have to define the knowledge of the Greek language, because it will be obvious that Greek teacher know Greek language).

As XML in get response it will look like this:

```
<cooperation-conditions>
            <student-studies-mobility-spec>
                <sending-hei-id>auth.gr</sending-hei-id>
[...]
                <receiving-hei-id>uw.edu.pl</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>en</language>
                    <cefr-level>B2</cefr-level>
                </recommended-language-skill>
[...]
                <eqf-level>6</eqf-level>
[...]
            </student-studies-mobility-spec>

            <student-studies-mobility-spec>
                <sending-hei-id>auth.gr</sending-hei-id>
[...]
                <receiving-hei-id>uw.edu.pl</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>en</language>
                    <cefr-level>B2</cefr-level>
                </recommended-language-skill>
                <recommended-language-skill>
                    <language>pl</language>
                    <cefr-level>A2</cefr-level>
                </recommended-language-skill>
                <recommended-language-skill>
                    <language>ru</language>
                    <cefr-level>B2</cefr-level>
                </recommended-language-skill>
[...]
                <eqf-level>8</eqf-level>
[...]
            </student-studies-mobility-spec>

            <staff-teacher-mobility-spec>
                <sending-hei-id>auth.gr</sending-hei-id>
[...]
                <receiving-hei-id>uw.edu.pl</receiving-hei-id>
[...]
                <recommended-language-skill>
                    <language>en</language>
                    <cefr-level>C1</cefr-level>
                </recommended-language-skill>
[...]
            </staff-teacher-mobility-spec>
[...]
```
