### ISSUE TITLE
Workflow for approving agreements

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#68]
During testing we encountered various interpretations of the workflow suggested at https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v6/example-scenario and I would therefore like to ask the designers of the API for clarification of certain things:

**Negotiation and signing of a new IIA**

In point 6, A will probably want to compare their copy to the copy received from B. Let’s say that:
1. B’s copy contains some minor discrepancies, which the A-coordinator decides to ignore (such as missing sending-ounit-id or other wording of other-info-terms etc.) and proceeds to point 7. Is this scenario acceptable?
2. B’s copy contains discrepancies which the A-coordinator decides not to accept. Now the A-coordinator needs to contact the B-coordinator outside of EWP (e.g. by e-mail) and tell them what is unacceptable. B’s system cannot automatically assume anything from the contents of A’s copy – i.e. it cannot assume that A’s copy is an answer (counter offer) to B’s proposition. Is this correct?
3. B’s copy contains discrepancies which the A-coordinator decides to accept and reflect in their agreement. So A proceeds to point 7 and then back to point 1 to reflect the changes in their copy (or the other way round – first reflects the changes in their IIA and then accepts B’ copy – both scenarios are possible, right?).
So in general, A can go back to point 1 how many times it wishes and similarly B can go back to point 5 repeatedly until a consensus is reached. And what is or isn’t a consensus is a business decision and can vary for each agreement. Is this correct?
And this "going back" can happen even after the Approval has been received from partner, right?

Another question concerns the signing-date – Is it true that this element should, for the partner side, contain the date on which the first approval was delivered for this IIA copy? If yes, then it follows that each partner can have different signing dates on their IIA because their respective copies could have been approved on different days. And in case the Approval CNR is delayed or the Approval get request is delayed, the value may not actually reflect the signing date of the partner but the date on which the signature/approval was received, correct? 

**Negotiation and signing of an amendment to an existing IIA**

In practice, many IIAs are amended after they are signed. This can happen for example after one or several years. So let’s say that coordinators agreed (for example by e-mail) to amend something. Both copies are already approved. So now I assume that the example scenario will run again from point 1 and that the other partner should interpret the conditions-hash change as a request for approving the amendment, right?

To make things more complicated - Let’s consider that the mobility exchange should happen between A’s unit 123 and B’s unit 456 and that the A-coordinator decided to put this information into the ounit-id elements at the IIA level, while the B-coordinator put it in the sending/receiving-ounit-id elements for each cooperation condition in their copy. Now consider that they decide to change the unit. A can reflect this change in their IIA without B’s approval, while B needs A’s approval. Is this really possible? Or is there a fundamental difference between these two approaches, which would justify the fact that the first approach is not “covered” by the conditions-hash, while the latter is?

**Comment by kamil-olszewski-uw** [comment]
> B’s copy contains some minor discrepancies, which the A-coordinator decides to ignore (such as missing sending-ounit-id or other wording of other-info-terms etc.) and proceeds to point 7. Is this scenario acceptable?

Yes. Of course, the user takes the business responsibility of accepting this slight difference, and must think carefully about whether it is actually irrelevant.

> B’s copy contains discrepancies which the A-coordinator decides not to accept. Now the A-coordinator needs to contact the B-coordinator outside of EWP (e.g. by e-mail) and tell them what is unacceptable. B’s system cannot automatically assume anything from the contents of A’s copy – i.e. it cannot assume that A’s copy is an answer (counter offer) to B’s proposition. Is this correct?

No. If the coordinator of A does not want approve B's copy, the IIA in system A must be an exact counterproposal. Of course, A can contact B to explain why such changes are proposed. The only exception that comes to my mind is that A does not have a copy of IIA in the system at all and does not want to sign an agreement with B. But rather, the practice is such that the mutual willingness to sign IIA and some (or even complete) negotiations regarding cooperation conditions take place outside EWP, and only then IIA ends up in the system of one of the partners.

> B’s copy contains discrepancies which the A-coordinator decides to accept and reflect in their agreement. So A proceeds to point 7 and then back to point 1 to reflect the changes in their copy (or the other way round – first reflects the changes in their IIA and then accepts B’ copy – both scenarios are possible, right?).

Both scenarios are possible, but the latter is better because it's better for B to see the updated copy in A's system as soon as B receives approval CNR.

> So in general, A can go back to point 1 how many times it wishes and similarly B can go back to point 5 repeatedly until a consensus is reached. And what is or isn’t a consensus is a business decision and can vary for each agreement. Is this correct?

Yes. And, as I mentioned, it's okay to talk about changes outside EWP.

> And this "going back" can happen even after the Approval has been received from partner, right?

Theoretically yes. But here we have to be careful. It may turn out that the partner system will not allow it or the partner simply does not want it for business purposes. So we should first talk with our partner outside EWP, whether we will correct the old IIA or sign a new one.

> Another question concerns the signing-date – Is it true that this element should, for the partner side, contain the date on which the first approval was delivered for this IIA copy? If yes, then it follows that each partner can have different signing dates on their IIA because their respective copies could have been approved on different days. And in case the Approval CNR is delayed or the Approval get request is delayed, the value may not actually reflect the signing date of the partner but the date on which the signature/approval was received, correct?

Yes. The signing dates of the two partners may be different in the way you presented or for different reasons. For example, it can be that A approved IIA and is waiting for B's approval. A may, for example:

- enter current signing date at the moment of approval of B's copy (if B does not approve A's copy, then B can delete its signing date),
- enter current signing date at the moment of processing B's approval of A's copy,
- enter signing date identical to B's siging date.

In fact, A can enter any date as long as it has some business sense. And neither of the two systems should base their behavior on the value of this date in the context of the data exchange by the EWP.

> In practice, many IIAs are amended after they are signed. This can happen for example after one or several years. So let’s say that coordinators agreed (for example by e-mail) to amend something. Both copies are already approved. So now I assume that the example scenario will run again from point 1 and that the other partner should interpret the conditions-hash change as a request for approving the amendment, right?

As I wrote, theoretically yes, but we must be careful and we must also arrange everything with the partner in advance. We must also remember that by modifying cooperation conditions, creating new hashes and making new approvals, we are losing proof of what cooperation conditions we agreed to in previous years. If both sides agree and there is no risk of a dispute, the IIA can be corrected. But maybe the new IIA will be a safer solution.

> To make things more complicated - Let’s consider that the mobility exchange should happen between A’s unit 123 and B’s unit 456 and that the A-coordinator decided to put this information into the ounit-id elements at the IIA level, while the B-coordinator put it in the sending/receiving-ounit-id elements for each cooperation condition in their copy. Now consider that they decide to change the unit. A can reflect this change in their IIA without B’s approval, while B needs A’s approval. Is this really possible? Or is there a fundamental difference between these two approaches, which would justify the fact that the first approach is not “covered” by the conditions-hash, while the latter is?

From the documentation of `ounit-id` element at the IIA level: `If given, then it refers to the unit within the partner HEI's organizational structure, which is the actual partner of this agreement. Agreements can be signed between units, not only between HEIs`

This means that we define this unit when the entire university is not a partner of the IIA - for example, when the agreement is signed by an autonomous branch of the university, or when the faculty itself takes care of all the formalities, official matters, financing, etc., and the university IRO does not even know about this IIA.

**Comment by jiripetrzelka** [comment]
Thank you for the answers. There is one thing, which is still not clear to me:

> > B’s copy contains discrepancies which the A-coordinator decides not to accept. Now the A-coordinator needs to contact the B-coordinator outside of EWP (e.g. by e-mail) and tell them what is unacceptable. B’s system cannot automatically assume anything from the contents of A’s copy – i.e. it cannot assume that A’s copy is an answer (counter offer) to B’s proposition. Is this correct?
> 
> No. If the coordinator of A does not want approve B's copy, the IIA in system A must be an exact counterproposal. Of course, A can contact B to explain why such changes are proposed. The only exception that comes to my mind is that A does not have a copy of IIA in the system at all and does not want to sign an agreement with B. But rather, the practice is such that the mutual willingness to sign IIA and some (or even complete) negotiations regarding cooperation conditions take place outside EWP, and only then IIA ends up in the system of one of the partners.

This is a bit more complicated because once B's proposal reaches system A, the A-coordinator is notified and after some time (minutes, hours, days), the A-coordinator goes to the system, imports the B-IIA into A-IIA and changes something to make the counterproposal. Then the A-coordinator forwards this new version internally to the A-signatory (institutional coordinator, dean, etc.) for approval and only then is the counterproposal published in A's IIA GET endpoint. But during this period, B can still invoke A's GET endpoint as many times it wishes. How does B get to know from A's GET endpoint that the decision is still pending? Should the A's GET endpoint perhaps return empty response until the counterproposal is ready? (But this could be interpreted by B as A having deleted the IIA and having lost interest in the cooperation as such.) Or is it up to B to compare the last conditions-hash of A's IIA with the new one and consider the A's GET response to be a counterproposal only if the conditions-hash has changed and otherwise consider the A's IIA status to be "counterproposal pending"?

If we dig a bit deeper into the sequence of actions, this is what happens:
1. B sends IIA CNR for B's IIA copy
2. (delay until A's queue is invoked and B's IIA is retrieved, say couple of minutes)
3. B's IIA copy is retrieved and A-coordinator is notified
4. (delay until A-coordinator takes some action)
5. A-coordinator takes an action and A's IIA re-enters internal approval process
6. (delay until internal approval process is finished)
7. A's IIA counterproposal is ready

The question is what should A's GET endpoint return in points 2, 4, and 6. 
My opinion is:
- In point 2, the A-system is yet unaware of B's proposal and must therefore serve the original A's IIA copy.
- In point 4, the A-system could theoretically hide the A's IIA from the GET endpoint, or keep the original A-IIA copy. What is the preferred option?
- In point 6, it makes sense to me that A's IIA is hidden from A's GET endpoint because it is not ready for approval by B.

Aside from the fact that B can invoke A's IIA GET endpoint at any time on its own, A can also send its IIA CNR to B during point 2 and possibly during point 4 because the A-coordinator may want to make some minor changes in its IIA's contents that do not have any impact on A's IIA conditions-hash. Is my assuption correct that whether B's GET requests to A's IIA GET endpoint in points 2 and 4 are or aren't triggered by a CNR is totally irrelevant?

**Comment by kamil-olszewski-uw** [comment]
In my opinion original A's IIA copy should be served all the time before point 7 in your scenario. This will apparently show partner B that counterproposal processing is pending.

At points 3-6 you could also serve downloaded B's counterproposal, but in this case, we risk that B will be pleased to see an updated IIA in A's system and approve it first.

Hiding the IIA while it is processed can, as you figured out, confuse your partner.

**Comment by janinamincer-daszkiewicz** [comment]
Issue is continued in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/100.
