### ISSUE TITLE
Still on IIA conditions-hash: why not simplify by changing the point of view?

### ISSUE THREAD

**Issue by demilatof** [erasmus-without-paper/ewp-specs-api-iias#72]
I apologize, but I think that until the official documentation doesn't publish the pseudo algorithm to create the string to hash, this argument will be discussed again and again.
That string to hash MUST be the same for everyone, no one has to guess what the counterpart may have done to assemble it.

Unluckily after months on Github we still read in the get-response.xsd of ewp-specs-api-iias:

"The SHA-256 digest of the cooperation-conditions element but ***excluding* `sending-contact` and `receiving-contact` subelements**. Before calculating the hash, the cooperation-conditions element should be normalized using Exclusive XML Canonicalization."

On my opinion the core of the problem stays in the response.xsd of ewp-specs-api-iias-approval:

"the server has to call the IIAs get API and _compare the hash received in the response **with the hash independently calculated** from the cooperation conditions received in that response_.  **If both hashes are identical**, the agreement can be approved."

This means that right now  we have to compute the hash on "their" XML, after removing some information; in other words this mean that we are modifying in some way the XML, voiding the assumption that we have to work on the exact XML received.

Why have we to compute again the hash?
I cannot trust that the other Hei know how to compute a hash? On what basis, using my own interpretation of an algorithm that is not commonly accepted?
Who will decide which hash is wrong? The client or the server failed to compute the hash?

_**I think that the trick is quite easy**_, it's enough to understand what the hash should be used for: on my opinion it is useful to be sure that I'm approving that IIA and not a version modified by the partner for whatever reason.

Therefore in the approval I've to write back the hash code arrived with the get response and stored in my DB together with the full XML received. **_The couple (IIA_id, hash) is a key that identify for sure that IIA and not a modified one_**.
 
It doesn't matter how I've compared my IIA version with the one received, I can compare them element by element or visually by mean of an operator.. Once decided, **I approve the counterpart's IIA identified by the IIA_id and hash computed with its own algorithm**; and I write in the approval the hash received with the get response.
The counterpart has to verify that the approval is still valid for that IIA, maybe computing again the hash on its xml version, but in this case there's no problem: _it's enough that the counterpart keep on using its same algorithm, whatever it is_.

Now, the question is: if the above scenario is right, why not adopt it modifying the official specification?
The above text in the response.xsd of ewp-specs-api-iias-approval could become:

"the digest MUST be the one received in the IIAs API get response for the exact version of the agreement that is being approved"

Any contribution is welcomed

**Comment by janinamincer-daszkiewicz** [comment]
We have to calculate the hash on our side because we want to be sure that what we approve is exactly what we have obtained from the partner (their XML, their hash) and that these two are compliant.

If hashes do not match, yes, we should contact the partner and find out the source of mismatch (error in  their algorithm, error in your algorithm, bad will).

I don't think developers are willing to store partner's version of IIA in XML format in their system. Also if XML and hash are not compliant how can you later prove that this is exactly what you have got from the partner? It becomes tricky.

We made some proposal how to avoid hashes, but for some reasons developers prefer to stick to hashes, see:
https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/48#issuecomment-922460127

**Comment by demilatof** [comment]
Many thanks for your answer.

I really can't understand: if you receive a set of data "signed" by a hash, you accept that data identified by that hash.
It's useless to compute it again, what can make the xml and hash not compliant?
Without a common algorithm you can contact the partner to use the same algorithm, but then it can be wrong for another partner. Doing so brings nowhere, I don't want to implement a system where an algorithm is good for A partner but not for B partner.
We are still pointing out this, and it's December just now.

Moreover: what does it means: "if XML and hash are not compliant how can you later prove that this is exactly what you have got from the partner?"
I store the XML in a table where the key is IIA_ID and hash. This is what I've received from partner and this is what I accept.
Do you really think that computing again the hash could be a proof that it is exactly what I have got from the partner?
A proof of what? Against whom? 
Which of us will have to change its concept of the algorithm? My hei or the partner? Who decides this? On which basis?

I think that if we want that hash should be similar to a digital sign, we have to transmit the exact, untouched and untouchable data processed to obtain the hash.
Could even be a redundant tag, without elements that spec says to remove.

I don't know on what basis you think that developer are not willing to store the partner version of IIA in XML format.
There are several reasons to store the XML:
1) there are a lot of information useless to manage and storing in dedicated field; the program extract the elements really useful and store the remaining in a single block (XML) for future uses (in case of necessity)
2) to log what happened and to know the exact IIA that we agreed with. Who approve an IIA without keeping a copy?

But even if you save all data in the DB, and not the XML, you can mark that data with the received IIA_id and hash and you will always know that you approved that IIA and not another one.

It seems to me that the EWP vision doesn't take care of databases, but thinks that  everything goes on fly in XML format, nothing persistent. Instead the first thing is to materialize the received data and identify them with an exact key (IIA_id, hash).
And this is essential for universities that have hundred and hundred of agreements.

In the thread https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/48#issue-825765232 I don't read that developers prefer to stick to hashes, but that developers don't want to change the approach at this point introducing new problems. 

I think that they want to go on with hash, but even be sure that everybody adopt the same solution.
On my opinion there are two easy solutions without modifying to much what they have already did:

1) sharing the same algorithm or exposing the exact string on a single line to compute for hash, between tags `<toHash>` and `</toHash>`
2) indicating that there is no need to compute again the hash received, just saving it together with IIA_id, and writing it in the approval. Every developer will choose how to bind iia_id, hash and data: storing XML or single fields.

**Comment by j-be** [comment]
> That string to hash MUST be the same for everyone, no one has to guess what the counterpart may have done to assemble it.

If we wouldn't be 3 months before deadline: I fully agree, this needs to be thought over again. Where we are right now: It is imho. to late to change fundamentals of the API. We'll all need this up and running in a month or two, because as (as far as I understood it) we'll need this online by the start of the next application season, which should be March 1st 2022. I agree that what we have is far from ideal, over-complicated, and does not provide any benefit for the complexity it adds. But we are up against a deadline. So I think it is a really bad idea to scrap this and rethink it.

>  that I'm approving that IIA and not a version modified by the partner for whatever reason.

As far as I am concerned, with the hash as it is right now, it would require serious criminal intent to do so unnoticed, even without everybody checking the hash before approval: in case of doubt you'll still need to proof where you got that hash from in the first place. So you'd need something like: 

* prepare an IIA and get the hash
* use that hash on a preliminary IIA
* get the preliminary IIA approved
* swap out the IIAs

We trust our partners don't have that amount of criminal intent.

> I store the XML in a table where the key is IIA_ID and hash

It is my understanding, that the main EWP architecture as specified [here](https://github.com/erasmus-without-paper/ewp-specs-architecture) most prominently in the [CNR section](https://github.com/erasmus-without-paper/ewp-specs-architecture#broadcasting-changes-cnr-apis) strongly recommends against storing data not under your control persistently. But I also think that parts of that very section would need a rework, since CNRs are required now (I wonder if that is because people started doing the very thing the spec recommends not to do). So I could see how one would take all of this with a grain of salt.

Finally, I still think, that we should define a way how to compute these hashes deterministically (like every 2 IIAs with the same logical content lead to the same hash). We'd get some useful new features, e.g. linking the IIAs automatically, as I could just (A) compute the hash on my copy and (B) ask the partner system if it has anything matching that. Approval would also be implicit, i.e. if 2 partners have an IIA for each other carrying the same hash an IIA can be considered mutually approved. Like I already detailed [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/48#issuecomment-881501326) this should be achievable quite easily, but I seem to be the only one liking the idea.

**Comment by sascoms** [comment]
I am sure all should have heard the news but if not a quick note:

**_The deadline for using EWP for IIA exchanges has been postponed to 31 December 2022._**

That means we have enough time for discussing and changing fundamentals of the API where needed.

We hope we can use this period for fixing the problems, creating better solutions and improving the APIs.

**Comment by demilatof** [comment]
@sascoms 
I haven't received any communication yet, but if confirmed is a good news

**Comment by casualtimer** [comment]
@sascoms We haven't got any news on that too. Would help if true though. Does anyone have an official source link confirming the postponement?

**Comment by sascoms** [comment]
@casualtimer @demilatof 

As well as I know, Turkish and Dutch NAs have already announced it to their HEIs.

Could you also please confirm it from DOs in your NAs?

**Comment by janinamincer-daszkiewicz** [comment]
Official message from DG EAC.

[058 - The European Student Card Initiative–Further clarifications regarding the timeline of digitalisation of IIAs for HE mobility[1].pdf](https://github.com/erasmus-without-paper/ewp-specs-api-iias/files/7817268/058.-.The.European.Student.Card.Initiative.Further.clarifications.regarding.the.timeline.of.digitalisation.of.IIAs.for.HE.mobility.1.pdf)

**Comment by madiken21** [comment]
Since conditions hash purpose is to be sure that IIA partner copy has not changed since last download and approvment, why not just generate a  new random alpha-numeric string each time a partner edit his cooperations conditions and send it during approvment ? like proposal changes key in learning agreements ?
