### ISSUE TITLE
Number of partners to IIA

### ISSUE THREAD

**Issue by serkanUH** [erasmus-without-paper/ewp-specs-api-iias#75]
On the latest stable-6 release I see that the minimum and maximum number of partners in a IIA is 2. So this numbers is always exact 2. 

- Does this mean that V6 is not backwards compatible with V4 ? 
- Can partners exchange IIA's and IIA approval while using different versions of IIA's ( V4 - V6 ) ? Are these compatible to each other ? 
- How will this limitation of 2 facilitate the [Blended intensive programmes](https://erasmus-plus.ec.europa.eu/programme-guide/part-b/key-action-1/mobility-project-for-higher-education-students-and-staff) where the minimum required partners is 3  ?

**Comment by kamil-olszewski-uw** [comment]
Major changes to the version number (leftmost digit) are due to backward incompatibility. See here: https://github.com/erasmus-without-paper/ewp-specs-management/tree/v1.2.1#backward-compatibility

Thus, data exchange between V4 and V6 (and between any different major versions in any EWP API) is not possible.

Currently, the IIAs API has not yet been developed to meet the needs of BIPs.
