### ISSUE TITLE
Business level statistics - IIA

### ISSUE THREAD

**Issue by janinamincer-daszkiewicz** [erasmus-without-paper/ewp-specs-api-iias#82]
During the Infrastructure Forum meeting today we discussed the possibility to gather the following data from each HEI in the EWP Network:

From each HEI, those IIAs which meet **all** of the conditions:
- have been signed by home HEI,
- flag in-effect is on (have been active at some point in time),
- have been approved by the partner.

Do you agree that this statistics will properly show the picture of system in operation and activity of local IRO staff?
Could you. please, check if this description is clear and you can easily gather such data?

Could you share this statistics with EWP tech team? As yet unofficially, we will not yet share it with anybody outside the team.

After we gather some opinions we will ask DG EAC for their opinion and their ideas how we will be gathering such (similar) data in the future.

**Comment by kamil-olszewski-uw** [comment]
It depends on what exactly we want to report. If we want to know about the number of all signed and valid LAs, we should skip the point "the last existing version of LA is approved". If we want to know the number of all signed LAs, for which there is no need to perform any additional actions (i.e. they do not have any modification proposals awaiting approval of the receiving university), then this point should be taken into account.

**Comment by janinamincer-daszkiewicz** [comment]
I have got statistics from some of you and see that the description should be more precise. We are interested only in IIAs for the new Erasmus+ programme shared under EWP. Let's try to calculate such numbers:

1. Number of IIAs created in the local system, waiting for  further processing.
2. Number of IIAs signed/approved by the local HEI but not yet by the partner HEI.
3. Number of IIAs signed/approved by the partner HEI but not yet by the local HEI.
4. Number of IIAs signed/approved by both local HEI and partner HEI.

Please, let us know when you switch on the flag in-effect.

**Comment by georgschermann** [comment]
in-effect is set as soon as there are both signatures / approvals

**Comment by ipnreddy** [comment]
MoveON sets in-effect as soon as it is signed by the local HEI i.e. point 2

**Comment by sascoms** [comment]
In ErasmusJET, the in-effect flag can only be set once the IIA is signed by both of the partners.

There is no automatic set operation during the sign/approval process.

And if the IIA is signed by both partners, the IRO staff themselves decide when to set in-effect=yes, as this will affect the IIA to be displayed/used in mobility application forms.

**Comment by RuudHaverlag** [comment]
In OSIRIS in-effect is set when both parties have signed/approved.

**Comment by georgschermann** [comment]
> And if the IIA is signed by both partners, the IRO staff themselves decide when to set in-effect=yes, as this will affect the IIA to be displayed/used in mobility application forms.

in our system the in-effect for EWP is separate from the activation for applications, etc.
so it may be in-effect but not used, since it may be restricted by other settings

**Comment by jiripetrzelka** [comment]
In ISOIS, the in-effect is on if our copy has ever been approved by partner, either by EWP or by other means.

**Comment by LDeprez** [comment]
In OASIS (ugent.be), the in-effect is set to true as soon as the agreement is
1.  signed locally AND
2.  approved/signed by the partner, no matter how partner signed/approved: 
      - on paper, 
      - by EWP approval of our local copy of the agreement or 
      - by partner signature on the partner copy of the agreement where the partner copy is mapped to our local copy.

**Comment by LDeprez** [comment]
This is the feedback of Ghent University:
**1/ Number of IIA created in the local system, waiting or further processing**
What is the purpose of this data point?
For us, this can e.g. include:
•	Agreement that are not yet shared via EWP but that at one point will be shared 
•	local agreements with EWP partners that do not support IIA endpoints (yet) 
**2/ Number of IIAs signed/approved by the local HEI but not yet by the partner HEI**
Clear
**3/ Number of IIAs signed/approved by the partner HEI but not yet by the local HEI**
Clear
**4/ Number of IIAs signed/approved by both local HEI and partner HEI**
Clear
**5/ Number of IIA which
5.1 have been signed by local HEI**
For us: this includes agreements that were locally signed but reverted due to feedback by the partner. It includes also IIA’s from 4/.
**5.2 flag in-effect is on (have been active at some point)**
In OASIS (ugent.be), the in-effect is set to true as soon as the agreement is signed locally AND approved/signed by the
partner, no matter how partner signed/approved:
a) on paper,
b) by EWP approval of our local copy of the agreement or
c) by partner signature on the partner copy of the agreement where the partner copy is mapped to our local copy.
At this moment, we cannot distinguish between a (non EWP) and c (EWP). We could provide only b) or a+b+c
**5.3 have been approved by the partner**
Clear

We don’t see the added value of subitems under 5, as they resemble item 2 and 4 and are prone to different interpretations amongst applications.

**Comment by janinamincer-daszkiewicz** [comment]
Our proposal for today is the following (we will discuss it on 2022-06-22 at the Infrastructure Forum meeting):

1. Number of IIAs created in the local system which can be fetched by the partner HEI.
2. Number of IIAs created in the local system which have been approved by the partner HEI but the matching copies of the partner have not been approved by the local HEI.
3. Number of IIAs created in the local system which have not been approved by the partner HEI but the matching copies of the partner have been approved by the local HEI. 
4. Number of IIAs created in the local system which have been approved by the partner HEI and the matching copies of the partner have been approved by the local HEI. 

Is this more clear now?

**Comment by sascoms** [comment]
Let me translate these into developer language :)

1. Number of IIAs created in the local system which can be fetched by the partner.
`iia-origin = local`
`published-in-IIA-INDEX = yes`


2. Number of IIAs created in the local system which have been approved by the partner HEI but the matching copies of the partner have not been approved by the local HEI.
`iia-origin = local`
`local-hei-approved-partner-copy = no`
`partner-hei-approved-your-local-copy = yes`


3. Number of IIAs created in the local system which have not been approved by the partner HEI but the matching copies of the partner have been approved by the local HEI.
`iia-origin = local`
`local-hei-approved-partner-copy = yes`
`partner-hei-approved-your-local-copy = no`

4. Number of IIAs created in the local system which have been approved by the partner HEI and the matching copies of the partner have been approved by the local HEI. 
`iia-origin = local`
`local-hei-approved-partner-copy = yes`
`partner-hei-approved-your-local-copy = yes`

_* local-hei means you/your-hei_

Corrections and/or improvements are welcome.

**Comment by janinamincer-daszkiewicz** [comment]
IIA Stats enpoint: https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/stats.md.

**Comment by milsorm** [comment]
So definitely that's meaning is not "how many IIA is processed in such HEI" but "how many IIA is originated in such HEI". If any HEI is passive in creation and only approve all IIAs send to them, they will still report 0 and that's not mean "they don't do it" but only "they don't originate process". Am I right?

A creates IIA and sends it to B. B prepare counter-offer and send it back to A. Than A approved and B approved lately. In that case A is reporting 1 fetchable and 1 both approved, B is reporting 0 fetchable and 0 both approved. Am I right?

I am asking because interpretation of statistics portal among clients is different and discussions "they don't use it properly" or "that provider is not able to handle IIAs properly" appears. But that numbers tell nothing about usage of IIA at HEIs, it is only about "who first start the negotiation process". Am I right?

**Comment by milsorm** [comment]
And much more - interpretation as charts are pretty ridiculous. What mean chart with number of IIAs per country or per provider? It doesn't mean HOW MANY IIAs is prepared/approved by country or by provider's system. it only means "where are active HEIs who started that process", nothing else. It is necessary to add some comments/information to charts for better interpretation of results.

**Comment by janinamincer-daszkiewicz** [comment]
> So definitely that's meaning is not "how many IIA is processed in such HEI" but "how many IIA is originated in such HEI". If any HEI is passive in creation and only approve all IIAs send to them, they will still report 0 and that's not mean "they don't do it" but only "they don't originate process". Am I right?

That would mean that this HEI is not handling IIAs properly. There will always be two copies, one at each partner. If partner A creates IIA with partner B, also partner B (in his system) will create IIA with partner A.

> A creates IIA and sends it to B. B prepare counter-offer and send it back to A. Than A approved and B approved lately. In that case A is reporting 1 fetchable and 1 both approved, B is reporting 0 fetchable and 0 both approved. Am I right?

No. A sends CNR to B. B gets IIA and stores it in his system. So B of course will also have 1 fetchable. B makes changes in his version, sends CNR to A. A gets changes. If A is happy, both will approve both copies. A and B will have 1 fetchable and 1 approved by both. B could not send approval if B would not have his copy, because B has to share IIA identifier with A.

> I am asking because interpretation of statistics portal among clients is different and discussions "they don't use it properly" or "that provider is not able to handle IIAs properly" appears. But that numbers tell nothing about usage of IIA at HEIs, it is only about "who first start the negotiation process". Am I right?

No, you are not.
There is Information icon at https://stats.erasmuswithoutpaper.eu/chart. It was reviewed by many colleagues, I hope it helps.
