### ISSUE TITLE
Signing date and signing contact

### ISSUE THREAD

**Issue by JoepDemey** [erasmus-without-paper/ewp-specs-api-iias#91]
We have created a function in our software to copy an incoming IIA to an IIA on our side. I was just wondering what to do with signing contact and signing date on the "iia partner" property of our partner. Can we just copy them into our version, that has not yet been approved? On the other hand, an IIA approval has no signing date or signing contact, so we can only get them from the partner version of the IIA, right?

**Comment by kamil-olszewski-uw** [comment]
If the contact on the partner's side is well known to you and you are 100% sure that this person will be the signing contact for particular IIA, you can add them yourself to your IIA copy. However, in a typical scenario, the contact data should be retrieved from the partner. A partner's signing date should always be downloaded from the partner, as it is they who determine it.

If contact or signing date appears in the partner copy, you can download this data and put it in your copy at any time, because it does not affect the hash and the approval process.

However, if your partner has not yet approved your copy of the IIA and is already providing a signing date, this is strange and you should ask the partner why they are providing a signing date for something they have not yet signed.

**Comment by sascoms** [comment]
What if the partner has approved the IIA but there is no signing date on it?

**Comment by kamil-olszewski-uw** [comment]
It's up to you. You may, for example, decide that in-effect flag set to true and mutual approval is enough, but ask the partner for the missing date anyway.

In the near future, when we introduce the IIAs statuses, we will probably link the signing date with specific statuses, and from then on, some statuses will require the date and for other statuses the date will be not allowed.

**Comment by ghost** [comment]
> We have created a function in our software to copy an incoming IIA to an IIA on our side. I was just wondering what to do with signing contact and signing date on the "iia partner" property of our partner. Can we just copy them into our version, that has not yet been approved? On the other hand, an IIA approval has no signing date or signing contact, so we can only get them from the partner version of the IIA, right?

If you are copying it only from your copies, maybe you should copy an existing IIA from the approved IIA copy of partner?

**Comment by bvalero-umh** [comment]
Can we assume then that the signing/approval date and contact are the same concepts?

The only case I think there can be a problem is, for instance:

1. A approves an agreement (remote copy of B)
2. A updates in its local copy the signing date with the current date
3. For technical reasons or whatever, B receives the approval notification the next day, and interprets as approval date the time of receiving the approval.
4. Signing date for A is not the same as approval date for B

Anyway I think this kind of misalignments will be rare.

In general, specification should be improved to clarify as much as possible the difference between signing and approval, if any, especially in the "signing" fields and in the approval API.

**Comment by janinamincer-daszkiewicz** [comment]
According to [Mandatory Business Requirements](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/resources/mandatory_business_requirements_IIA.pdf)
`The meaning of "signed" IIA: the EWP Spec has no interest whether an iia has been internally officially signed or not by some institutional coordinator. Partners may include the ‘signing-contact’ or the ‘signing-date’ but this should not be taken as an approval. An IIA is approved by the approval API.`
